apiVersion: apps/v1
kind: Deployment
metadata:
  name: logan-app-operator
  namespace: logan
spec:
  replicas: 0
  selector:
    matchLabels:
      name: logan-app-operator
  template:
    metadata:
      labels:
        name: logan-app-operator
    spec:
      serviceAccountName: logan-app-operator
      containers:
        - name: logan-app-operator
          # Replace this with the built image name
          image: logancloud/logan-app-operator:latest
          command:
            - logan-app-operator
          args: ["--config", "/etc/logan/config.yaml", "--zap-devel", "--zap-level", "info"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 512Mi
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "logan-app-operator"
            - name: LOGAN_ENV
              value: "test"
            - name: BIZ_ENVS
              value: "LAST_DEPLOY"
          volumeMounts:
            - mountPath: /etc/logan
              name: logan-app-operator-config
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: logan-app-operator-webhook
      volumes:
        - name: logan-app-operator-config
          configMap:
            name: logan-app-operator-config
        - name: logan-app-operator-webhook
          secret:
            secretName: logan-app-operator-webhook
  strategy:
    type: Recreate